In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data=pd.read_csv("/content/Social_Network_Ads.csv")

In [3]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
data.isna().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [7]:
data['Gender'].unique()

data['Gender'].value_counts()

Gender
Female    204
Male      196
Name: count, dtype: int64

In [8]:
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()

In [9]:
data['Gender']=label_encoder.fit_transform(data['Gender'])

In [10]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       1   19            19000          0
1  15810944       1   35            20000          0
2  15668575       0   26            43000          0
3  15603246       0   27            57000          0
4  15804002       1   19            76000          0

We will implement the following algorithms on top of this data and check which algorithm gives us the least value of FP and FN

- Logistic Regression
- Decision Trees
- Random Forest

In [11]:
x=data.drop(['Purchased'],axis=1) #independent columns
y=data['Purchased'] #dependent column

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.75)

In [13]:
#logistic regression
from sklearn.linear_model import LogisticRegression
model_1=LogisticRegression()

In [14]:
model_1.fit(x_train,y_train)

LogisticRegression()

In [15]:
predictions_1=model_1.predict(x_test)

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_1=confusion_matrix(y_test,predictions_1)
ac_1=accuracy_score(y_test,predictions_1)

In [18]:
#decision trees
from sklearn.tree import DecisionTreeClassifier
model_2=DecisionTreeClassifier()

In [19]:
model_2.fit(x_train,y_train)

DecisionTreeClassifier()

In [20]:
predictions_2=model_2.predict(x_test)

In [21]:
cm_2=confusion_matrix(y_test,predictions_2)
ac_2=accuracy_score(y_test,predictions_2)

In [22]:
#random forest
from sklearn.ensemble import RandomForestClassifier
model_3=RandomForestClassifier()

In [23]:
model_3.fit(x_train,y_train)

RandomForestClassifier()

In [24]:
predictions_3=model_3.predict(x_test)

In [25]:
cm_3=confusion_matrix(y_test,predictions_3)
ac_3=accuracy_score(y_test,predictions_3)

In [29]:
print(cm_1) #FP=6, FN=15
print(cm_2) #FP=6, FN=9
print(cm_3) #FP=7, FN=6

[[58  6]
 [15 21]]
[[58  6]
 [ 9 27]]
[[57  7]
 [ 6 30]]


In [30]:
print(ac_1,"accuracy obtained by Logistic Regression")
print(ac_2,"accuracy obtained by Decision Tree")
print(ac_3,"accuracy obtained by Random Forest")

0.79 accuracy obtained by Logistic Regression
0.85 accuracy obtained by Decision Tree
0.87 accuracy obtained by Random Forest
